### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mikerkelly87** [Alfano93/ceph-toolkit#22]
On the network testing ansible commands there is no `-a` between `shell` and the module arguments

**Comment by mikerkelly87** [comment]
To clarify this is in the file ceph-install-18_04.md

**Comment by mikerkelly87** [comment]
Also on the lines:
db_size: "200G" # 4% of the drive size
AND:
db_size: "200G" # 4% of osd drive size

It is a little confusing at first glance to know if the 4% should be based on the TOTAL storage of all the drives, or the storage of EACH drive.

**Comment by BjoernT** [comment]
per osd put i think we revise that even to a more like 1/30/300 gb role
