### ISSUE TITLE
Add udev rules to make SSDs show up as SSDs with Dell RAID cards

### ISSUE THREAD

**Issue by Alfano93** [Alfano93/ceph-toolkit#27]
Add task to create udev rules to make the OS recognize ssds as ssds and not the rotational disks it thinks it is. This is mostly an issue with DELL RAID cards

**Comment by mattkleifgen** [comment]
We can create a udev rule /etc/udev/rules.d/60-ssd.rules with something like the following.  It'll need to have the right scsi devices added.  It can be tested without reboot with "udevadm trigger", and should persist after reboot

# set non-rotating for SSDs
ACTION=="add|change", KERNEL=="sd[b-g]", ATTR{queue/rotational}="0"

**Comment by BjoernT** [comment]
We cant set it on scsi device names and much rather need to rely on model numbers or something else

**Comment by Alfano93** [comment]
Can it be assumed that the person deploying the cluster would know what drives are what medium?

**Comment by BjoernT** [comment]
Im wondering if we can get rotational speed from the controller and 0 = SSD as example so we could script it out

**Comment by Alfano93** [comment]
Just using echo to set the rotational value to 0 is not good enough. The value switches back to '1' on reboot. We will also need a way to make this persistent. 

```
root@Flareon:~# echo "0" > /sys/block/sdb/queue/rotational 

root@Flareon:~# for f in /sys/block/sd?/queue/rotational; do printf "$f is "; cat $f; done 

/sys/block/sda/queue/rotational is 1
/sys/block/sdb/queue/rotational is 0
/sys/block/sdc/queue/rotational is 1
/sys/block/sdd/queue/rotational is 1
/sys/block/sde/queue/rotational is 1
/sys/block/sdf/queue/rotational is 1
/sys/block/sdg/queue/rotational is 1

root@Flareon:~# reboot

Once the node comes back...

root@Flareon:~# for f in /sys/block/sd?/queue/rotational; do printf "$f is "; cat $f; done 
/sys/block/sda/queue/rotational is 1
/sys/block/sdb/queue/rotational is 1
/sys/block/sdc/queue/rotational is 1
/sys/block/sdd/queue/rotational is 1
/sys/block/sde/queue/rotational is 1
/sys/block/sdf/queue/rotational is 1
/sys/block/sdg/queue/rotational is 1

```

**Comment by Alfano93** [comment]
Setting everything in udev rules does make it stick, so forget what I put above

**Comment by Alfano93** [comment]
This was fixed with the N release. #50
