### ISSUE TITLE
Rados Gateway config changes for Nautilus

### ISSUE THREAD

**Issue by mikerkelly87** [Alfano93/ceph-toolkit#55]
Please add in the notes for the RADOS gateway setup that the `ceph_conf_overrides` section needs to be moved from `/opt/ceph-ansible/group_vars/rgws.yml` into `/opt/ceph-ansible/group_vars/all.yml`

Probably should go in:
`rados_gateway_install.md`
and
`rados_gateway_install_SSL.md`

**Comment by Alfano93** [comment]
@mikerkelly87 can you review the commit please so you are aware of the changes

**Comment by Alfano93** [comment]
fixed in f96ebbd011b464c2a21f3e3937cb68f26472c8ec
